"""empty message

Revision ID: 3e1c815f2841
Revises: cbe297e85554
Create Date: 2021-12-09 17:53:48.939039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1c815f2841'
down_revision = 'cbe297e85554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('instrumentation', sa.Text(), nullable=True))
    op.drop_column('song', 'instrumenation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('instrumenation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('song', 'instrumentation')
    # ### end Alembic commands ###
