"""empty message

Revision ID: 93b60db424f2
Revises: 412e879f986c
Create Date: 2021-12-13 17:13:35.663771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b60db424f2'
down_revision = '412e879f986c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('song', sa.Column('setlist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'song', 'setlist', ['setlist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_column('song', 'setlist_id')
    op.drop_table('setlist')
    # ### end Alembic commands ###
