"""empty message

Revision ID: cbe297e85554
Revises: 6e80d29df3fb
Create Date: 2021-12-09 17:53:06.368728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe297e85554'
down_revision = '6e80d29df3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('song', sa.Column('instrumenation', sa.Text(), nullable=True))
    op.alter_column('song', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('song', 'instrumentation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('instrumentation', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('song', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('song', 'instrumenation')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
